os: linux
dist: xenial
language: php

env:
  global:
    # GITHUB_TOKEN
    - secure: "TbH4BzxhThar4som8lrLvysZe2Unf7LNmbnBma9ZT7v6yYk1RLug9tIltCoktrIRsSuq6usspG1GjmWpb74KTJSXVs3BuR81hM7zH4DKkZZahqhVgz1uOno3qZHCO/K/hSBfS3gkIuTPuYmAOEaSWz26buKwZPQWlSWFWfo3+uvT6jaa+Ry+EWwbtpEQsp7ox3oOomIJg3jwUD9tP7xlyMHDDY1XC8X1uE09KefqUSxeN2id5Yb6kb21+iB9kONImGt0AqUSBOa7iwadizhBMGUs0b9IwVIG4+5V3zIATubqZOTGJQJ/z+XDCY6gUw42TmVThneZVdM9++7XU7mCuIh+5jE1tTgnxuLGubXAAFWLPZN0+VwMnkCCcdccFz313+pSCVgww2lIKn2Ij0fGt3OJyqik8kzDwE7YGuFWJYx21SXTiJy6nXj9T7UYEJbyNMq6PSA/QVUrfnikzJ5024NYs2MhnL7ZPuo364M6I7HkecRVvlSdsI04njjUYpCBVvR+sIEfBzL3YBq3kz8v2Q+V0lY6wsrGDfZdQ1KonbE3XC7ADZSVzzzwcSl2OWwamjbORgr03LoEwJZuk7nYDDzyJU7zwtu4XiagxdudJw+/V/xAhQo079MOiiOP91ZTFm4g18WvDrCSkDUGe3/SIlCy5ESWYQHHNUvaQjb9a28="
    # AWS_ACCESS_KEY_ID
    - secure: "JY3QycQYnUn14rUPJ3Dl10Hn2NmDmOdHjDhsB5ZUhIVZSHlzmr115geTSk2dNA3j/a9rTL3RkpZ3FEdyvQzyIflEdLaA+BEQ/loufV+61CCDJz7hRmMCp914YrI0c0nWisNTU8EBXlR3rGxqeP2cDLCTAYrc12FeVrRuMXIpXI5k5R/CHtzt3KeyK/W7ecaZ/w6+5P4ROMIE+Fqs0ZhhvtTjpIbzzfOKzjRrheStLQexPN0liV39cSB7ju7F9A43GlZ4bLec0mCv0oAqFBD5vWzvOkSOhKtSHnM5O7kM4ZEWPfTyxRB9UMIU4MDRDwYVSNGsgNdJMn+eV+vi5K2hqgGeutdhAt6jv8IRn82fkDX3G6gVRQcJ3H2RqWg43D/vNoNgnsfGHSMyR3BdqpPD0j58ZzZtkgudpC2rKbAzOK8vcADLiP4e6ZigNF0Fmm3DzO3k7n8Mpn2gSgEU7yqLJVyceVz5F7bGtQQNCqcjUOeYoZPh4mEVieN2xrWAzIrJUqbCiIGVP7kYnAX3qZP9jhFoUFAQID7X9yurdj47WySM7XNL/6KpRew5F7oQ3+H/bxs2LazfK30JcDEAWNw+G00+VUvmveqWVvJ6FXXNyTS3gtEFKSlHBm7THrNPkmpU3v3p/3wpyNeoVDXHm7eQaISVMay9QZCRZ8a62e/TSD0="
    # AWS_SECRET_ACCESS_KEY
    - secure: "KJfTP43Q23+nrpqtT4jzJZn7MQWjfHtfCei/V5w8cA3wc3ZCqxhxkrM5RrxIX4dW1tuq77N7sNeKklI+psasN1SqeAZuDJ3KsdmwjwRwSVeHBKF66AGdTfsvfQsmJVr43jzZuHUr3l3ofdPu5jldv1+Dg0Oyad4yO2jK7JaU+4XacSIDapliYDg6If1H7vve3eXBvyEj4bifFytqX0nygZ8vF2V2ZWprkIfsvVQQybcIOyhyY2bBTn69/WDP3D2VysN0lxu/vq4lsTDo70rEbC4xzXcPNx2U9QG+TrMAKjKaK5J8FgzjsI9lUVW6i5p452qnlw0Mg9VpBoBy/kRh+oZqGbxioVC4Filg77VL4TFlOulvIIDAwSbeokfJj0NVX8fs1cXARrsm8DKBhEFxUzgw13EIBx4o4937//Nqgh/pnC42vSvA9tKRF1A9LwI6HzOtRpz8QfP5+vddUSuizVrOPKXZFzFHsT0vW2eUcEieWUpw1qzNKTYjbezSaRkl1xLLez+gP/fgnsh+odLX8X+FcbS2A6gNfTAW6MABZyXXd9vUuOGkyvjvvoNRlBE/ef5411A3hhv/BYd+TkQxEQFChXlQlJ6fx+VxAypFWS4unfVlL35LcgvTAjARiwU5pp1//4TMjmP+tU+RMXI9QpS1ntLRSZP1X9XaN+6XvqE="

jobs:
  include:
    - stage: Draft The Release
      script: skip
      if: tag IS present && type = push
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file:
            - phpstan.phar
            - phpstan.phar.asc
          skip_cleanup: true
          draft: true
          name: $TRAVIS_TAG
          on:
            tags: true

    - stage: Update Playground
      name: Update Playground
      if: (branch = master) && type = push
      script:
        - cd playground-runner
        - composer install --no-dev
        - cp ../phpstan.phar vendor/phpstan/phpstan/phpstan.phar
        - cp ../phpstan vendor/phpstan/phpstan/phpstan
        - rm -rf vendor/phpstan/phpstan/.git
        - npm install -g serverless@1.83.0
        - serverless deploy

cache:
  directories:
    - $HOME/.composer/cache
