service: phpstan-runner2

provider:
    name: aws
    region: eu-west-1
    stage: prod
    versionFunctions: false
    httpApi:
      cors: true

plugins:
    - ./vendor/bref/bref

functions:
    main:
        handler: bref.php
        description: ''
        timeout: 20
        runtime: php-81
    ignoreErrors:
        handler: ignoreErrors.php
        runtime: php-81-fpm
        events:
          - httpApi:
              method: 'GET'
              path: /ignoreErrors
