# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Issue Bot Build"

on:
  pull_request:
    paths:
      - '.github/workflows/build-issue-bot.yml'
      - 'issue-bot/**'
  push:
    branches:
      - "1.8.x"
    paths:
      - '.github/workflows/build-issue-bot.yml'
      - 'issue-bot/**'

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        script:
          - "../phpstan analyse"
          - "vendor/bin/phpunit"
          - "vendor/bin/phpcs"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.0"

      - name: "Install PHP dependencies"
        working-directory: ./issue-bot
        run: "composer install --no-interaction --no-progress"

      - name: "Script"
        working-directory: ./issue-bot
        run: "${{ matrix.script }}"
