# From:
  # https://www.docker.com/blog/docker-github-actions/
  # https://github.com/metcalfc/docker-action-examples

name: Docker image nightly

on:
  push:
    branches:
      - "1.11.x"
    paths:
      - '.github/workflows/docker-nightly.yml'
      - 'docker/**'
      - 'phpstan'
      - '.phar-checksum'
      - 'bootstrap.php'

jobs:
  docker:
    runs-on: ubuntu-latest
    concurrency: docker-nightly-${{ github.ref }}-${{ matrix.docker-file }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker-file: "./docker/Dockerfile.php.8.0"
            image-tag-suffix: ""
          - docker-file: "./docker/Dockerfile.php.8.0"
            image-tag-suffix: "-php8.0"
          - docker-file: "./docker/Dockerfile.php.8.1"
            image-tag-suffix: "-php8.1"
          - docker-file: "./docker/Dockerfile.php.8.2"
            image-tag-suffix: "-php8.2"
          - docker-file: "./docker/Dockerfile.php.8.3"
            image-tag-suffix: "-php8.3"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./docker
          file: "${{ matrix.docker-file }}"
          build-args: |
            PHPSTAN_VERSION=1.11.x-dev#${{ github.sha }}
          push: true
          tags: "ghcr.io/phpstan/phpstan:nightly${{ matrix.image-tag-suffix }}"
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
