# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Extension tests"

on:
  workflow_call:
    inputs:
      ref:
        description: 'phpstan/phpstan ref to checkout'
        required: true
        type: string
      phar-checksum:
        description: 'PHAR checksum from reproducible build (please rebase)'
        required: true
        type: string

jobs:
  check-phar-checksum:
    name: "Check PHAR checksum"
    runs-on: "ubuntu-latest"
    outputs:
      checksum-result: ${{ steps.checksum-difference.outputs.result }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: "phpstan/phpstan"
          ref: ${{ inputs.ref }}
      - name: "Check PHAR checksum"
        id: checksum-difference
        run: |
          checksum=${{ inputs.phar-checksum }}
          if [[ $(head -n 1 .phar-checksum) != "$checksum" ]]; then
            echo "result=different" >> $GITHUB_OUTPUT
          else
            echo "result=same" >> $GITHUB_OUTPUT
          fi

  tests-extensions:
    name: "Extension Tests"

    runs-on: "ubuntu-latest"

    needs: check-phar-checksum
    if: "needs.check-phar-checksum.outputs.checksum-result == 'different'"

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        extension-name:
          - "phpstan-phpunit 1.4.x"
          - "phpstan-strict-rules 1.6.x"
          - "phpstan-mockery 1.1.x"
          - "phpstan-doctrine 1.5.x"
          - "phpstan-symfony 1.4.x"
          - "phpstan-php-parser 1.2.x"
          - "phpstan-deprecation-rules 1.2.x"
          - "phpdoc-parser 1.23.x"
          - "phpstan-nette 1.1.x"
          - "phpstan-dibi 1.1.x"
          - "phpstan-webmozart-assert 1.2.x"
          - "phpstan-beberlei-assert 1.1.x"
        exclude:
          - extension-name: "phpstan-mockery"
            php-version: "7.2"
          - extension-name: "phpstan-mockery"
            php-version: "7.3"
          - extension-name: "phpstan-phpunit"
            php-version: "7.2"
          - extension-name: "phpstan-doctrine"
            php-version: "7.2"
          - extension-name: "phpstan-doctrine"
            php-version: "8.3"
          - extension-name: "phpstan-doctrine"
            php-version: "8.4"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: "phpstan/phpstan"
          ref: ${{ inputs.ref }}

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-file: development
          ini-values: memory_limit=768M
          extensions: soap

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress --ignore-platform-reqs"

      - name: "Download phpstan.phar"
        uses: Wandalen/wretry.action@v3.5.0
        with:
          action: actions/download-artifact@v4
          with: |
            name: phar-file
          attempt_limit: 5
          attempt_delay: 1000

      - name: "Extension build"
        env:
          PHP_VERSION: ${{ matrix.php-version }}
        run: "./e2e/test-extension.sh ${{ matrix.extension-name }}"
