# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Integration tests"

on:
  pull_request:
    paths-ignore:
      - 'issue-bot/**'
      - 'website/**'
      - 'playground-api/**'
      - 'playground-runner/**'
  push:
    branches:
      - "1.8.x"
    paths-ignore:
      - 'issue-bot/**'
      - 'website/**'
      - 'playground-api/**'
      - 'playground-runner/**'

jobs:
  upload-phar:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - uses: actions/upload-artifact@v3
        with:
          name: phar-file
          path: phpstan.phar
  integration-tests:
    needs: upload-phar
    uses: phpstan/phpstan/.github/workflows/integration-tests.yml@1.8.x
    with:
      ref: ${{ github.ref }}
      phar-checksum: "always"
