# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Update playground API"

on:
  push:
    branches:
      - "1.11.x"
    paths:
      - '.github/workflows/update-playground-api.yml'
      - 'playground-api/**'

concurrency: playground_api

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: playground-api/package-lock.json

      - name: "Install dependencies"
        working-directory: ./playground-api
        run: "npm ci"

      - name: "Check"
        working-directory: ./playground-api
        run: "npm run check"

      - name: "Deploy"
        working-directory: ./playground-api
        env:
          AWS_DEFAULT_REGION: "eu-west-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.PLAYGROUND_RUNNER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PLAYGROUND_RUNNER_AWS_SECRET_ACCESS_KEY }}
        run: "npm run deploy"
