# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Check Website Links"

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ check_website_links ]

jobs:
  website-links:
    name: "Check for broken links"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Check for broken links"
        uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: 'https://phpstan.org/'
          resolve_before_filtering: 'true'
          exclude_url_prefix: 'mailto:,https://twitter.com,https://www.startupjobs.cz,https://www.shopware.com'
          verbose: 'true'
          max_retry_time: 30
          max_retries: 5
